## NUMPY

- Numpy provides a seamless way to manage numerical arrays in Python.
- It is the foundational pillar of some scientific computing Python modules.
- To use numpy you have to import the module into the notebook.

In [1]:
import numpy as np # naming convention

#### Dtypes
- It permits fine-grained specification of numbers types even though Python is dynamically typed.
- Example:

In [2]:
a = np.array([0], np.int16) # 16-bit integer
a.itemsize # in 8-bit bytes; Output: 2
a.nbytes # 2

2

In [3]:
a = np.array([0], np.int64) # 64-bit integer
a.itemsize # 8

8

##### Properties of numpy arrays
1. Numerical arrays follow the same pattern. Forexample:

In [4]:
a = np.array([1, 2, 3, 8], np.int64) # 64-bit integer
a.shape # (4, )

(4,)

2. You can't tack an extra element once the array is created. This is because Python does not allocate a block of memory which has been delienated and numpy doesn't too allocate memory and copy data without explicit instruction.Example:

In [5]:
n = np.array([1,2])
n[2] = 89 # IndexError

IndexError: index 2 is out of bounds for axis 0 with size 2

3. Once an array of a specific dtype has been created, you need to cast while assigning to that array type. Example:

In [ ]:
x = np.array(range(5), dtype = int)
x[0] = 1.3 # Float assignment does not match assignment
x # Output array

In [ ]:
x[0] = 'This is a string' # ValueError

#### Multidimensional Arrays
1. Follow the same pattern

In [ ]:
# Example
a = np.array([[1, 4], [8, 9]]) # If the dtype is omitted it picks the default
a # array([[1, 4], [8,9]])

In [ ]:
a.dtype, a.shape # dtype('int32'), (2, 2)

In [ ]:
a.flatten() # array([1, 4, 8, 9])

2. The maximum limit of the number of dimensions depends on the array configuration during numpy build (usually thirty-two). Numpy support different ways of creating multi-D arrays. Examples:

In [ ]:
a = np.arange(10) # Analogous to range
a # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.zeros((2, 2))
a #array([[0., 0.], [0., 0.]])

In [ ]:
a = np.ones((2,2))
a #array([[1., 1.], [1., 1.]])

In [ ]:
x,y = np.meshgrid([1,2,3], [23, 45])
x # array([[1, 2, 3], [1, 2, 3]])

In [ ]:
y # array([[5, 5, 5], [6, 6, 6]])

3. You can use function to create arrays. Example

In [ ]:
m = np.fromfunction(lambda i, j: abs(i-j) < 1, (4,4))
m #array([[ True, False, False, False], False,  True, False, False], [False, False,  True, False], [False, False, False,  True]])

4. Numpy arrays can have field names. Example:

In [7]:
f = np.zeros((2, 2), dtype = [('x', 'f4')])
f['x'] # array([[0., 0.], [0., 0.]], dtype=float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

5. They can be accessed by their attributes.

In [ ]:
# Example
x = np.array([(1,8), (2, 9), (3, 10), (4, 11)], 
             dtype=[('value', 'f4'), ('amount', 'c8')])
x['value'] # array([1., 2., 3., 4.], dtype=float32)

In [ ]:
y = x.view(np.recarray)
y.amount #array([ 8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j], dtype=complex64)

In [ ]:
y.value # array([1., 2., 3., 4.], dtype=float32)

#### Reshaping and Stacking Arrays
- Arrays can be stacked horizontally or vertically. This can be achieved by using the ```hstack``` or ```vstack``` methods for horizontal and vertical stacking repectively.
- Example:

In [8]:
x = np.arange(5)
y = np.array([10, 20, 30, 40, 50])

# Horizontal stacking
np.hstack([x, y]) # array([ 0,  1,  2,  3,  4, 10, 20, 30, 40, 50])

array([ 0,  1,  2,  3,  4, 10, 20, 30, 40, 50])

In [ ]:
# Vertical Stacking
np.vstack([x,y]) # array([[ 0,  1,  2,  3,  4],
                # [10, 20, 30, 40, 50]])

- ```dstack``` is used for if you want to stack i the third ```depth``` dimension. Numpy ```np.concatenate``` handles the general arbitrary dimension case.You may find ```np.c_``` or ```np.r_``` used to stack arrays column-wise and row-wise in some codes like ```scikit-learn```:

In [ ]:
# Columnwise
np.c_[x, x] 

In [ ]:
# row-wise
np.r_[x,x]

#### Duplicating Numpy Arrays
- ```repeat``` function in numpy is use dfro duplicating arrays.
- ```tile``` is a more generalized version that lays out  block matrix of the specified shape.

In [ ]:
x = np.arange(4)
np.repeat(x, 2) # array([0, 0, 1, 1, 2, 2, 3, 3])

In [ ]:
np.tile(x, (2, 1)) # array([[0, 1, 2, 3],
                           #[0, 1, 2, 3]])

In [ ]:
# Non-numerics like strings as items in the array
np.array(['a', 'b', 'cow', 'sheep'])# array(['a', 'b', 'cow', 'sheep'], dtype='<U5')

*Note:* 'U5' refers to a string lenght of 5, the longest string in the sequence.

- The arrays can be reshaped after creation.

In [ ]:
a = np.arange(10).reshape(2, 5)
a

- You can replace one of the dimensions above by '-1' i.e. ```reshape(-1,5)``` and Numpy will figure out the conforming other dimension.
- The array ```transpose``` method operation is the same as the .T attribute,

In [ ]:
a.transpose()

In [ ]:
a.T

- The Hermitian transpose which is a conjugate transpose with ```.H``` attribute.


#### Slicing, Logical Array Operations

- Numpy array slicing follows the same zero-indexed slicing logic as Python lists and strings.
- Example:

In [ ]:
x = np.arange(50).reshape(5, 10)
x

- Slicing along a given dimension we use the colon which means take all along the indicated dimension. Example:

In [ ]:
x[:, 5] # any row, 5th column

In [ ]:
x[0,:] # any column, 0th row

In [ ]:
x[1:3, 5:8]

In [9]:
y = np.arange(2*3*4).reshape(2,3,4) # Reshaping arrays
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
y[:,1,[2,1]] # index each dimension

- ```where``` function can find array elements according to a specific logical cereteria. Example

In [10]:
np.where(y % 2 == 0)

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2], dtype=int64))

In [ ]:
y[np.where(y % 2 == 0)]

In [ ]:
y[np.where(np.logical_and(y % 2 == 0, y<=20))] # Also logical_or, etc

- Numpy arrays can be indexed by logical Numpy arrays where only the corresponding ```True``` entries are selected. Example:

In [ ]:
a = np.arange(10).reshape((5,2))
a

In [ ]:
b = np.fromfunction(lambda i,j: abs(i-j) <= 1, (3,3))
b

#### Numpy Arrays and Memory
- Numpy uses a pass-by reference semantics so that slice operations are *views* into the arrays without implicit copying, which is consistent with Python's semantics.
- This is important more especially for large arrays which strip the available memory.
- This is achieved through slicing which creates a view and through indexing that creates copies.

##### a. Indexing
- If the indexing object is a non-tuple sequence object another Numpy array of type integer or boolean  or a tuple atleast one sequence object or Numpy array the indexing creates copies
- Forexample: To extend and copy an existing array in Numpy.

In [11]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x[:, [0,1,2,2]] # Notice the duplicated last dimension

In [ ]:
y = x[:, [0,1,2,2]] # Same as above but do not assign to y

- Because of advanced indexing y has its own memory for the most relevant parts of x were copied to y.

In [ ]:
# To prove we assign a new element to x and see that y is not updated

x[0,0] = 399 # Change the element in x
x # Updated with the new value at position 0,0

In [ ]:
y # Not changed

##### b. Slicing
- If we start over and construct y by slicing as shown below then the change we make does affect y, because a view is just a window in the same memory.

In [ ]:
x = np.ones((3,3))
y = x[:2, :2] # View of upper left piece
x[0,0] = 399 # Change value
x # See the change

In [ ]:
y

_Note:_ You can explicitly copy to force a copy without any indexing i.e. ```y = x.copy()```

###### Overlapping Numpy Arrays
- Manipulating memory using views is powerful especially for signal and image processing algorithms, that require overlapping fragments of memory. 
- Example: To show how to use advanced Numpy to create overlapping blocks that do not actually consume additional memory.

In [ ]:
from numpy.lib.stride_tricks import as_strided
x = np.arange(6).astype(np.int32)
y = as_strided(x, (7,4), (8,4)) # Overlpped entries
y

- The code creates a range of integers and then overlaps the entries to create a _7x4_ Numpy array. The final argument as_strided function are the strides which are the steps in bytes to move in the row nd column dimensions, respectively.
- Thus the resulting array steps 4 bytes in the column dimensions and 8 bytes in the row dimension. This is because the integer elements in the Numpy array are 4 bytes which  is equivalent to moving by one  element in the column dimension and by 2 elements in the row dimension.
- The second row starts at 8 bytes (two elements) fom the firt entry and then proceed by 4 bytes (by 1 element) in the column dimension ie 2, 3, 4,5.
- Most importantly memory is used in the resulting 7x4 Numpy array.
- Example: The code below demonstrates this by reassigning elements in the original x array. Changes are shown up in y because they point at the same allocated memory.

In [ ]:
x[::2] = 89 # Assign every other value
x

In [ ]:
y # Change appears because y is a view

_Note_ ```as_strided``` does not check that you stay within  that memory block bounds. So, if the size of the target matrix is not filled by the available data elements, the remaining elements will come from whatever bytes are at that memory location. There is no filling with default zeros or other strategy that defends memory block bounds. One defense is to explicitly control the dimensions as demostrated below:

In [ ]:
n = 8 # number of elements
x = np.arange(n) # Create array
k = 5 # Deired number of rows
y = as_strided(x,(k,n-k+1), (x.itemsize,) * 2)
y

#### Numpy Memory Data Structures

In [12]:
# 16 bit numpy array for exploration
x = np.array([1], dtype=np.int16)

# Checking the raw data using x.data attribute
bytes(x.data)

b'\x01\x00'

- Observe the orientation of the bytes
- Now change it to unsigned two-byte endian integer

In [ ]:
x = np.array([1], dtype='>u2')
bytes(x.data)

- Again notice the orientation of the bytes. This is what little/big endian means for data memory.
- Also we can create arrays directly from bytes directly using ```frombuffer```. Note the effects of using different ```dtypes```.
- Examples:

In [ ]:
np.frombuffer(b'\x00\x01', dtype=np.int16)

In [ ]:
np.frombuffer(b'\x00\x01', dtype=np.int8)

In [ ]:
np.frombuffer(b'\x00\x01', dtype='<u2')

- You can re-cast a numpy array to a different dtype or change the dtype of the view after it has been created. Casting copies the data.

In [ ]:
x = np.frombuffer(b'\x00\x01', dtype = np.int8)
x # array([0,1], dtype=int8)

In [ ]:
y = x.astype(np.int16)
y # array([0, 1], dtype=int16)

In [ ]:
y.flags['OWNDATA'] # y is a copy; True

- We can interpret the data using a vie too

In [ ]:
y = x.view(np.int16)
y # array([256], dtype=int16)

In [ ]:
y.flags['OWNDATA'] # y is a copy; False

**Note:** y is not new in memory it is just referencing the existing memory and reinterpreting it using a different type.

##### Numpy Memory Strides

_Stride:_ is the number of bytes to reach the next consecutive array element. 
- There is one stride per a dimension.
- Consider the following:

In [ ]:
x = np.array([[1,2,3], [7,8,9]], dtype=np.int8)
bytes(x.data) # b'\x01\x02\x03\x07\x08\t'

In [ ]:
x.strides # (3, 1)

- Thus if we want to index x[1,2] we have to use the following offset:

In [ ]:
offset = 3*1 + 2*1
x.flat[offset]

#### Array Element-wise Operations
- The usual pairwise arithmetic operations are element-wise in Numpy. Example:

In [ ]:
x * 3

In [ ]:
x/x.max()

**Note**
- It is easy to mess in operations such as x -= x.T for Numpy arrays. In general this should be avoided since they make it hard to find bugs.

#### Universal Functions.
- ```ufunct``` are Numpy fuctions optimized used to compute Numpy arrays at the C-order level i.e. outside the Python interpreter.
- Example: Let us compute the trigonometric sine:

In [ ]:
x = np.linspace(0,1,20)
np.sin(x)

- Numpy's sine function does not need extra semantics because the computing occurs in the Numpy's C-code. This is unlike Python's sine which deals with a single variable at a time and it puts the output in a list.

#### Numpy Data Input/Output
- Numpy makes it easy to move data in and out of files:

In [ ]:
x = np.loadtxt('text.txt', delimiter=',', skiprows=1)
x

In [ ]:
# each column with different dtype
x = np.loadtxt('text.txt', delimiter=',', skiprows=1, dtype='f4, i4')
x

- Numpy arrays can be saved with the corresponding ```np.savetxt``` function.

#### Linear Algebra