In [1]:
import numpy as np

In [2]:
# Creating an empty 1D array 
np.empty(5)

array([2.12199579e-314, 1.19043964e-311, 5.41495948e-321, 3.79442416e-321,
       2.04721870e-306])

In [3]:
# empty 1D array specifying the data type
np.empty(2, np.int64)

array([ 7476672199825507592, -2794357734169970252], dtype=int64)

In [4]:
# Creating an array that is spaced linearly using the linspace() function
x = np.linspace(0,20, num=5)
x

array([ 0.,  5., 10., 15., 20.])

In [5]:
# An array of a specified interval i.e. 20
np.arange(0,100, 20)

array([ 0, 20, 40, 60, 80])

In [6]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [7]:
# Specifying the data type i.e. np.int32
y = np.arange(0,100, 5, dtype=np.int32)
y

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [8]:
# Checking the attributes of the y array
y.shape

(20,)

In [9]:
y.size

20

In [10]:
y.ndim

1

In [11]:
y.dtype

dtype('int32')

In [15]:
np.loadtxt('text.txt', delimiter=',', skiprows=1)

array([[0., 0.],
       [1., 1.],
       [2., 4.],
       [3., 9.]])